services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: drab-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
      - "3080:6333"  # Additional port for web UI access
    volumes:
      - qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__WEB_UI__ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdrant_storage: