export const trainingData = [
  // Basic addition (comprehensive range)
  { input: '0+0', output: 0 },
  { input: '0+1', output: 1 },
  { input: '0+2', output: 2 },
  { input: '0+3', output: 3 },
  { input: '0+4', output: 4 },
  { input: '0+5', output: 5 },
  { input: '1+0', output: 1 },
  { input: '1+1', output: 2 },
  { input: '1+2', output: 3 },
  { input: '1+3', output: 4 },
  { input: '1+4', output: 5 },
  { input: '1+5', output: 6 },
  { input: '1+6', output: 7 },
  { input: '1+7', output: 8 },
  { input: '1+8', output: 9 },
  { input: '1+9', output: 10 },
  { input: '2+1', output: 3 },
  { input: '2+2', output: 4 },
  { input: '2+3', output: 5 },
  { input: '2+4', output: 6 },
  { input: '2+5', output: 7 },
  { input: '2+6', output: 8 },
  { input: '2+7', output: 9 },
  { input: '2+8', output: 10 },
  { input: '2+9', output: 11 },
  { input: '3+1', output: 4 },
  { input: '3+2', output: 5 },
  { input: '3+3', output: 6 },
  { input: '3+4', output: 7 },
  { input: '3+5', output: 8 },
  { input: '3+6', output: 9 },
  { input: '3+7', output: 10 },
  { input: '3+8', output: 11 },
  { input: '3+9', output: 12 },
  { input: '4+1', output: 5 },
  { input: '4+2', output: 6 },
  { input: '4+3', output: 7 },
  { input: '4+4', output: 8 },
  { input: '4+5', output: 9 },
  { input: '4+6', output: 10 },
  { input: '4+7', output: 11 },
  { input: '4+8', output: 12 },
  { input: '4+9', output: 13 },
  { input: '5+1', output: 6 },
  { input: '5+2', output: 7 },
  { input: '5+3', output: 8 },
  { input: '5+4', output: 9 },
  { input: '5+5', output: 10 },
  { input: '5+6', output: 11 },
  { input: '5+7', output: 12 },
  { input: '5+8', output: 13 },
  { input: '5+9', output: 14 },
  { input: '6+1', output: 7 },
  { input: '6+2', output: 8 },
  { input: '6+3', output: 9 },
  { input: '6+4', output: 10 },
  { input: '6+5', output: 11 },
  { input: '6+6', output: 12 },
  { input: '6+7', output: 13 },
  { input: '6+8', output: 14 },
  { input: '6+9', output: 15 },
  { input: '7+1', output: 8 },
  { input: '7+2', output: 9 },
  { input: '7+3', output: 10 },
  { input: '7+4', output: 11 },
  { input: '7+5', output: 12 },
  { input: '7+6', output: 13 },
  { input: '7+7', output: 14 },
  { input: '7+8', output: 15 },
  { input: '7+9', output: 16 },
  { input: '8+1', output: 9 },
  { input: '8+2', output: 10 },
  { input: '8+3', output: 11 },
  { input: '8+4', output: 12 },
  { input: '8+5', output: 13 },
  { input: '8+6', output: 14 },
  { input: '8+7', output: 15 },
  { input: '8+8', output: 16 },
  { input: '8+9', output: 17 },
  { input: '9+1', output: 10 },
  { input: '9+2', output: 11 },
  { input: '9+3', output: 12 },
  { input: '9+4', output: 13 },
  { input: '9+5', output: 14 },
  { input: '9+6', output: 15 },
  { input: '9+7', output: 16 },
  { input: '9+8', output: 17 },
  { input: '9+9', output: 18 },

  // Basic subtraction (comprehensive)
  { input: '1-0', output: 1 },
  { input: '1-1', output: 0 },
  { input: '2-0', output: 2 },
  { input: '2-1', output: 1 },
  { input: '2-2', output: 0 },
  { input: '3-0', output: 3 },
  { input: '3-1', output: 2 },
  { input: '3-2', output: 1 },
  { input: '3-3', output: 0 },
  { input: '4-0', output: 4 },
  { input: '4-1', output: 3 },
  { input: '4-2', output: 2 },
  { input: '4-3', output: 1 },
  { input: '4-4', output: 0 },
  { input: '5-0', output: 5 },
  { input: '5-1', output: 4 },
  { input: '5-2', output: 3 },
  { input: '5-3', output: 2 },
  { input: '5-4', output: 1 },
  { input: '5-5', output: 0 },
  { input: '6-1', output: 5 },
  { input: '6-2', output: 4 },
  { input: '6-3', output: 3 },
  { input: '6-4', output: 2 },
  { input: '6-5', output: 1 },
  { input: '6-6', output: 0 },
  { input: '7-1', output: 6 },
  { input: '7-2', output: 5 },
  { input: '7-3', output: 4 },
  { input: '7-4', output: 3 },
  { input: '7-5', output: 2 },
  { input: '7-6', output: 1 },
  { input: '7-7', output: 0 },
  { input: '8-1', output: 7 },
  { input: '8-2', output: 6 },
  { input: '8-3', output: 5 },
  { input: '8-4', output: 4 },
  { input: '8-5', output: 3 },
  { input: '8-6', output: 2 },
  { input: '8-7', output: 1 },
  { input: '8-8', output: 0 },
  { input: '9-1', output: 8 },
  { input: '9-2', output: 7 },
  { input: '9-3', output: 6 },
  { input: '9-4', output: 5 },
  { input: '9-5', output: 4 },
  { input: '9-6', output: 3 },
  { input: '9-7', output: 2 },
  { input: '9-8', output: 1 },
  { input: '9-9', output: 0 },
  { input: '10-1', output: 9 },
  { input: '10-2', output: 8 },
  { input: '10-3', output: 7 },
  { input: '10-4', output: 6 },
  { input: '10-5', output: 5 },
  { input: '10-6', output: 4 },
  { input: '10-7', output: 3 },
  { input: '10-8', output: 2 },
  { input: '10-9', output: 1 },
  { input: '10-10', output: 0 },

  // Basic multiplication (full tables 0-9)
  { input: '0*0', output: 0 },
  { input: '0*1', output: 0 },
  { input: '0*2', output: 0 },
  { input: '0*3', output: 0 },
  { input: '0*4', output: 0 },
  { input: '0*5', output: 0 },
  { input: '0*6', output: 0 },
  { input: '0*7', output: 0 },
  { input: '0*8', output: 0 },
  { input: '0*9', output: 0 },
  { input: '1*0', output: 0 },
  { input: '1*1', output: 1 },
  { input: '1*2', output: 2 },
  { input: '1*3', output: 3 },
  { input: '1*4', output: 4 },
  { input: '1*5', output: 5 },
  { input: '1*6', output: 6 },
  { input: '1*7', output: 7 },
  { input: '1*8', output: 8 },
  { input: '1*9', output: 9 },
  { input: '2*0', output: 0 },
  { input: '2*1', output: 2 },
  { input: '2*2', output: 4 },
  { input: '2*3', output: 6 },
  { input: '2*4', output: 8 },
  { input: '2*5', output: 10 },
  { input: '2*6', output: 12 },
  { input: '2*7', output: 14 },
  { input: '2*8', output: 16 },
  { input: '2*9', output: 18 },
  { input: '3*0', output: 0 },
  { input: '3*1', output: 3 },
  { input: '3*2', output: 6 },
  { input: '3*3', output: 9 },
  { input: '3*4', output: 12 },
  { input: '3*5', output: 15 },
  { input: '3*6', output: 18 },
  { input: '3*7', output: 21 },
  { input: '3*8', output: 24 },
  { input: '3*9', output: 27 },
  { input: '4*0', output: 0 },
  { input: '4*1', output: 4 },
  { input: '4*2', output: 8 },
  { input: '4*3', output: 12 },
  { input: '4*4', output: 16 },
  { input: '4*5', output: 20 },
  { input: '4*6', output: 24 },
  { input: '4*7', output: 28 },
  { input: '4*8', output: 32 },
  { input: '4*9', output: 36 },
  { input: '5*0', output: 0 },
  { input: '5*1', output: 5 },
  { input: '5*2', output: 10 },
  { input: '5*3', output: 15 },
  { input: '5*4', output: 20 },
  { input: '5*5', output: 25 },
  { input: '5*6', output: 30 },
  { input: '5*7', output: 35 },
  { input: '5*8', output: 40 },
  { input: '5*9', output: 45 },
  { input: '6*0', output: 0 },
  { input: '6*1', output: 6 },
  { input: '6*2', output: 12 },
  { input: '6*3', output: 18 },
  { input: '6*4', output: 24 },
  { input: '6*5', output: 30 },
  { input: '6*6', output: 36 },
  { input: '6*7', output: 42 },
  { input: '6*8', output: 48 },
  { input: '6*9', output: 54 },
  { input: '7*0', output: 0 },
  { input: '7*1', output: 7 },
  { input: '7*2', output: 14 },
  { input: '7*3', output: 21 },
  { input: '7*4', output: 28 },
  { input: '7*5', output: 35 },
  { input: '7*6', output: 42 },
  { input: '7*7', output: 49 },
  { input: '7*8', output: 56 },
  { input: '7*9', output: 63 },
  { input: '8*0', output: 0 },
  { input: '8*1', output: 8 },
  { input: '8*2', output: 16 },
  { input: '8*3', output: 24 },
  { input: '8*4', output: 32 },
  { input: '8*5', output: 40 },
  { input: '8*6', output: 48 },
  { input: '8*7', output: 56 },
  { input: '8*8', output: 64 },
  { input: '8*9', output: 72 },
  { input: '9*0', output: 0 },
  { input: '9*1', output: 9 },
  { input: '9*2', output: 18 },
  { input: '9*3', output: 27 },
  { input: '9*4', output: 36 },
  { input: '9*5', output: 45 },
  { input: '9*6', output: 54 },
  { input: '9*7', output: 63 },
  { input: '9*8', output: 72 },
  { input: '9*9', output: 81 },

  // Division (comprehensive)
  { input: '1/1', output: 1 },
  { input: '2/1', output: 2 },
  { input: '2/2', output: 1 },
  { input: '3/1', output: 3 },
  { input: '3/3', output: 1 },
  { input: '4/1', output: 4 },
  { input: '4/2', output: 2 },
  { input: '4/4', output: 1 },
  { input: '5/1', output: 5 },
  { input: '5/5', output: 1 },
  { input: '6/1', output: 6 },
  { input: '6/2', output: 3 },
  { input: '6/3', output: 2 },
  { input: '6/6', output: 1 },
  { input: '7/1', output: 7 },
  { input: '7/7', output: 1 },
  { input: '8/1', output: 8 },
  { input: '8/2', output: 4 },
  { input: '8/4', output: 2 },
  { input: '8/8', output: 1 },
  { input: '9/1', output: 9 },
  { input: '9/3', output: 3 },
  { input: '9/9', output: 1 },
  { input: '10/1', output: 10 },
  { input: '10/2', output: 5 },
  { input: '10/5', output: 2 },
  { input: '10/10', output: 1 },
  { input: '12/1', output: 12 },
  { input: '12/2', output: 6 },
  { input: '12/3', output: 4 },
  { input: '12/4', output: 3 },
  { input: '12/6', output: 2 },
  { input: '12/12', output: 1 },
  { input: '15/1', output: 15 },
  { input: '15/3', output: 5 },
  { input: '15/5', output: 3 },
  { input: '15/15', output: 1 },
  { input: '16/1', output: 16 },
  { input: '16/2', output: 8 },
  { input: '16/4', output: 4 },
  { input: '16/8', output: 2 },
  { input: '16/16', output: 1 },
  { input: '18/1', output: 18 },
  { input: '18/2', output: 9 },
  { input: '18/3', output: 6 },
  { input: '18/6', output: 3 },
  { input: '18/9', output: 2 },
  { input: '18/18', output: 1 },
  { input: '20/1', output: 20 },
  { input: '20/2', output: 10 },
  { input: '20/4', output: 5 },
  { input: '20/5', output: 4 },
  { input: '20/10', output: 2 },
  { input: '20/20', output: 1 },
  { input: '21/1', output: 21 },
  { input: '21/3', output: 7 },
  { input: '21/7', output: 3 },
  { input: '21/21', output: 1 },
  { input: '24/1', output: 24 },
  { input: '24/2', output: 12 },
  { input: '24/3', output: 8 },
  { input: '24/4', output: 6 },
  { input: '24/6', output: 4 },
  { input: '24/8', output: 3 },
  { input: '24/12', output: 2 },
  { input: '24/24', output: 1 },
  { input: '25/1', output: 25 },
  { input: '25/5', output: 5 },
  { input: '25/25', output: 1 },

  // Powers (comprehensive)
  { input: '0^1', output: 0 },
  { input: '0^2', output: 0 },
  { input: '0^3', output: 0 },
  { input: '1^1', output: 1 },
  { input: '1^2', output: 1 },
  { input: '1^3', output: 1 },
  { input: '1^4', output: 1 },
  { input: '1^5', output: 1 },
  { input: '2^1', output: 2 },
  { input: '2^2', output: 4 },
  { input: '2^3', output: 8 },
  { input: '2^4', output: 16 },
  { input: '2^5', output: 32 },
  { input: '3^1', output: 3 },
  { input: '3^2', output: 9 },
  { input: '3^3', output: 27 },
  { input: '3^4', output: 81 },
  { input: '4^1', output: 4 },
  { input: '4^2', output: 16 },
  { input: '4^3', output: 64 },
  { input: '5^1', output: 5 },
  { input: '5^2', output: 25 },
  { input: '5^3', output: 125 },
  { input: '6^1', output: 6 },
  { input: '6^2', output: 36 },
  { input: '7^1', output: 7 },
  { input: '7^2', output: 49 },
  { input: '8^1', output: 8 },
  { input: '8^2', output: 64 },
  { input: '9^1', output: 9 },
  { input: '9^2', output: 81 },
  { input: '10^1', output: 10 },
  { input: '10^2', output: 100 },

  // Natural language addition
  { input: 'what is 1 plus 1', output: 2 },
  { input: 'what is 2 plus 2', output: 4 },
  { input: 'what is 3 plus 3', output: 6 },
  { input: 'what is 4 plus 4', output: 8 },
  { input: 'what is 5 plus 5', output: 10 },
  { input: 'add 1 and 2', output: 3 },
  { input: 'add 2 and 3', output: 5 },
  { input: 'add 3 and 4', output: 7 },
  { input: 'add 4 and 5', output: 9 },
  { input: 'add 5 and 6', output: 11 },
  { input: 'sum of 1 and 1', output: 2 },
  { input: 'sum of 2 and 3', output: 5 },
  { input: 'sum of 4 and 6', output: 10 },
  { input: 'total of 3 and 7', output: 10 },
  { input: 'combine 4 and 6', output: 10 },

  // Natural language subtraction
  { input: 'subtract 1 from 2', output: 1 },
  { input: 'subtract 2 from 5', output: 3 },
  { input: 'subtract 3 from 7', output: 4 },
  { input: 'subtract 4 from 10', output: 6 },
  { input: 'take 1 from 3', output: 2 },
  { input: 'take 2 from 6', output: 4 },
  { input: 'take 3 from 8', output: 5 },
  { input: 'what is 5 minus 2', output: 3 },
  { input: 'what is 8 minus 3', output: 5 },
  { input: 'what is 10 minus 4', output: 6 },

  // Natural language multiplication
  { input: '1 times 1', output: 1 },
  { input: '2 times 2', output: 4 },
  { input: '2 times 3', output: 6 },
  { input: '3 times 3', output: 9 },
  { input: '3 times 4', output: 12 },
  { input: '4 times 4', output: 16 },
  { input: '4 times 5', output: 20 },
  { input: '5 times 5', output: 25 },
  { input: 'multiply 2 by 3', output: 6 },
  { input: 'multiply 3 by 4', output: 12 },
  { input: 'multiply 4 by 5', output: 20 },
  { input: 'what is 3 multiplied by 4', output: 12 },
  { input: 'what is 5 multiplied by 6', output: 30 },

  // Natural language division
  { input: 'divide 4 by 2', output: 2 },
  { input: 'divide 6 by 3', output: 2 },
  { input: 'divide 8 by 4', output: 2 },
  { input: 'divide 10 by 5', output: 2 },
  { input: '4 divided by 2', output: 2 },
  { input: '6 divided by 3', output: 2 },
  { input: '8 divided by 4', output: 2 },
  { input: '10 divided by 5', output: 2 },
  { input: 'what is 4 over 2', output: 2 },
  { input: 'what is 8 over 4', output: 2 },
  { input: 'what is 12 over 6', output: 2 },

  // Natural language powers
  { input: '2 power 2', output: 4 },
  { input: '3 power 2', output: 9 },
  { input: '4 power 2', output: 16 },
  { input: '5 power 2', output: 25 },
  { input: 'what is 2 power 2', output: 4 },
  { input: 'what is 3 power 2', output: 9 },
  { input: 'what is 4 power 2', output: 16 },
  { input: '2 squared', output: 4 },
  { input: '3 squared', output: 9 },
  { input: '4 squared', output: 16 },
  { input: '5 squared', output: 25 },
  { input: '6 squared', output: 36 },
  { input: '7 squared', output: 49 },
  { input: '8 squared', output: 64 },
  { input: '9 squared', output: 81 },
  { input: '10 squared', output: 100 },
  { input: '2 square', output: 4 },
  { input: '3 square', output: 9 },
  { input: '4 square', output: 16 },
  { input: '5 square', output: 25 },
  { input: '6 square', output: 36 },
  { input: '7 square', output: 49 },
  { input: '8 square', output: 64 },
  { input: '9 square', output: 81 },
  { input: '10 square', output: 100 },

  // Word numbers
  { input: 'zero plus zero', output: 0 },
  { input: 'zero plus one', output: 1 },
  { input: 'one plus zero', output: 1 },
  { input: 'one plus one', output: 2 },
  { input: 'one plus two', output: 3 },
  { input: 'two plus one', output: 3 },
  { input: 'two plus two', output: 4 },
  { input: 'two plus three', output: 5 },
  { input: 'three plus one', output: 4 },
  { input: 'three plus two', output: 5 },
  { input: 'three plus three', output: 6 },
  { input: 'four plus four', output: 8 },
  { input: 'five plus five', output: 10 },
  { input: 'one times one', output: 1 },
  { input: 'one times two', output: 2 },
  { input: 'two times one', output: 2 },
  { input: 'two times two', output: 4 },
  { input: 'two times three', output: 6 },
  { input: 'three times one', output: 3 },
  { input: 'three times two', output: 6 },
  { input: 'three times three', output: 9 },
  { input: 'three times four', output: 12 },
  { input: 'four times four', output: 16 },
  { input: 'four times five', output: 20 },
  { input: 'five times five', output: 25 },
  { input: 'two minus one', output: 1 },
  { input: 'three minus one', output: 2 },
  { input: 'three minus two', output: 1 },
  { input: 'four minus one', output: 3 },
  { input: 'four minus two', output: 2 },
  { input: 'five minus two', output: 3 },
  { input: 'six times seven', output: 42 },
  { input: 'seven times six', output: 42 },
  { input: 'eight minus three', output: 5 },
  { input: 'nine plus one', output: 10 },
  { input: 'ten divided by two', output: 5 },
  { input: 'twelve divided by three', output: 4 },
  { input: 'fifteen divided by five', output: 3 },
];
