export const trainingData = [
  // Basic addition (expanded)
  { input: '1+1', output: 2 },
  { input: '2+2', output: 4 },
  { input: '3+3', output: 6 },
  { input: '4+4', output: 8 },
  { input: '5+5', output: 10 },
  { input: '1+2', output: 3 },
  { input: '2+3', output: 5 },
  { input: '3+4', output: 7 },
  { input: '4+5', output: 9 },
  { input: '5+3', output: 8 },
  { input: '6+2', output: 8 },
  { input: '7+3', output: 10 },
  { input: '8+2', output: 10 },
  { input: '9+1', output: 10 },
  { input: '10+5', output: 15 },
  { input: '7+8', output: 15 },
  { input: '6+7', output: 13 },
  { input: '11+9', output: 20 },
  { input: '13+7', output: 20 },
  { input: '14+6', output: 20 },
  { input: '16+4', output: 20 },
  { input: '12+8', output: 20 },
  { input: '15+5', output: 20 },

  // Natural language addition (expanded)
  { input: 'what is 2 plus 2', output: 4 },
  { input: 'add 3 and 5', output: 8 },
  { input: 'what will I get if I add 7 with 3', output: 10 },
  { input: 'sum of 4 and 6', output: 10 },
  { input: '2 into 2', output: 4 },
  { input: 'what is 1 into 1', output: 2 },
  { input: 'combine 5 and 7', output: 12 },
  { input: 'total of 8 and 2', output: 10 },
  { input: 'put together 9 and 3', output: 12 },
  { input: 'what do you get when you add 6 to 4', output: 10 },
  { input: 'if I have 5 and add 5', output: 10 },
  { input: 'give me 3 plus 9', output: 12 },
  { input: 'what is the total of 7 and 5', output: 12 },
  { input: 'find the sum of 8 and 4', output: 12 },
  { input: 'how much is 6 added to 8', output: 14 },
  { input: 'calculate 9 plus 7', output: 16 },

  // Basic subtraction (expanded)
  { input: '10-5', output: 5 },
  { input: '8-3', output: 5 },
  { input: '15-7', output: 8 },
  { input: '20-12', output: 8 },
  { input: '9-4', output: 5 },
  { input: '11-6', output: 5 },
  { input: '14-8', output: 6 },
  { input: '18-9', output: 9 },
  { input: '25-15', output: 10 },
  { input: '30-20', output: 10 },
  { input: '12-7', output: 5 },
  { input: '16-9', output: 7 },
  { input: '13-5', output: 8 },
  { input: '17-8', output: 9 },
  { input: '19-11', output: 8 },
  { input: '22-14', output: 8 },
  { input: '24-16', output: 8 },

  // Natural language subtraction (expanded)
  { input: 'subtract 4 from 10', output: 6 },
  { input: 'take 3 from 8', output: 5 },
  { input: 'what is 15 minus 5', output: 10 },
  { input: '10 minus 4', output: 6 },
  { input: 'remove 2 from 7', output: 5 },
  { input: 'take away 5 from 12', output: 7 },
  { input: 'what is left when you subtract 3 from 11', output: 8 },
  { input: 'deduct 4 from 14', output: 10 },
  { input: 'what remains after taking 6 from 16', output: 10 },
  { input: 'minus 7 from 18', output: 11 },
  { input: 'reduce 20 by 8', output: 12 },
  { input: 'how much less is 5 from 13', output: 8 },

  // Basic multiplication (expanded)
  { input: '2*3', output: 6 },
  { input: '4*5', output: 20 },
  { input: '8*9', output: 72 },
  { input: '3*7', output: 21 },
  { input: '6*4', output: 24 },
  { input: '5*6', output: 30 },
  { input: '7*8', output: 56 },
  { input: '9*3', output: 27 },
  { input: '2*9', output: 18 },
  { input: '4*7', output: 28 },
  { input: '5*5', output: 25 },
  { input: '6*6', output: 36 },
  { input: '7*7', output: 49 },
  { input: '8*8', output: 64 },
  { input: '9*9', output: 81 },
  { input: '2*4', output: 8 },
  { input: '3*5', output: 15 },
  { input: '4*6', output: 24 },
  { input: '5*7', output: 35 },
  { input: '6*8', output: 48 },
  { input: '3*8', output: 24 },
  { input: '4*9', output: 36 },

  // Natural language multiplication (expanded)
  { input: '2 times 3', output: 6 },
  { input: 'multiply 4 by 5', output: 20 },
  { input: 'what is 3 multiplied by 4', output: 12 },
  { input: '6 by 7', output: 42 },
  { input: 'what is 5 groups of 4', output: 20 },
  { input: 'how much is 3 lots of 8', output: 24 },
  { input: '7 multiplied with 6', output: 42 },
  { input: 'find the product of 4 and 9', output: 36 },
  { input: 'what do you get from 8 times 7', output: 56 },
  { input: 'calculate 6 times 5', output: 30 },
  { input: 'what is 9 groups of 4', output: 36 },
  { input: 'how many is 7 lots of 5', output: 35 },

  // Basic division (expanded)
  { input: '10/2', output: 5 },
  { input: '15/3', output: 5 },
  { input: '20/4', output: 5 },
  { input: '24/6', output: 4 },
  { input: '18/9', output: 2 },
  { input: '21/7', output: 3 },
  { input: '28/4', output: 7 },
  { input: '35/5', output: 7 },
  { input: '42/6', output: 7 },
  { input: '48/8', output: 6 },
  { input: '36/9', output: 4 },
  { input: '49/7', output: 7 },
  { input: '56/8', output: 7 },
  { input: '63/9', output: 7 },
  { input: '72/8', output: 9 },
  { input: '81/9', output: 9 },

  // Natural language division (expanded)
  { input: 'divide 10 by 2', output: 5 },
  { input: '15 divided by 3', output: 5 },
  { input: 'what is 20 over 4', output: 5 },
  { input: 'split 12 into 3 parts', output: 4 },
  { input: 'how many 4s are in 16', output: 4 },
  { input: 'what is 25 shared by 5', output: 5 },
  { input: 'break 30 into 6 groups', output: 5 },
  { input: 'how many times does 7 go into 21', output: 3 },
  { input: 'what is 32 split by 4', output: 8 },
  { input: 'divide 45 equally by 5', output: 9 },

  // Powers and squares (expanded)
  { input: '2^2', output: 4 },
  { input: '3^2', output: 9 },
  { input: '4^2', output: 16 },
  { input: '5^2', output: 25 },
  { input: '6^2', output: 36 },
  { input: '7^2', output: 49 },
  { input: '8^2', output: 64 },
  { input: '9^2', output: 81 },
  { input: '2^3', output: 8 },
  { input: '3^3', output: 27 },
  { input: '4^3', output: 64 },
  { input: '2^4', output: 16 },
  { input: '3^4', output: 81 },

  // Natural language powers (expanded)
  { input: '2 power 2', output: 4 },
  { input: 'what is 2 power 2', output: 4 },
  { input: '3 squared', output: 9 },
  { input: '4 square', output: 16 },
  { input: '5 square', output: 25 },
  { input: '6 square', output: 36 },
  { input: '7 square', output: 49 },
  { input: '8 square', output: 64 },
  { input: '9 square', output: 81 },
  { input: '5 raised to 2', output: 25 },
  { input: '2 to the power of 3', output: 8 },
  { input: '3 to the power of 3', output: 27 },
  { input: 'what is 4 squared', output: 16 },
  { input: 'find 6 to the second power', output: 36 },
  { input: 'calculate 7 squared', output: 49 },

  // Word numbers (expanded)
  { input: 'two plus two', output: 4 },
  { input: 'three times four', output: 12 },
  { input: 'five minus two', output: 3 },
  { input: 'ten divided by two', output: 5 },
  { input: 'one plus one', output: 2 },
  { input: 'six times seven', output: 42 },
  { input: 'eight minus three', output: 5 },
  { input: 'nine plus one', output: 10 },
  { input: 'four plus five', output: 9 },
  { input: 'seven minus four', output: 3 },
  { input: 'six plus six', output: 12 },
  { input: 'eight times two', output: 16 },
  { input: 'nine minus six', output: 3 },
  { input: 'four times five', output: 20 },
  { input: 'twelve divided by three', output: 4 },
  { input: 'fifteen divided by five', output: 3 },

  // More complex expressions (expanded)
  { input: 'what is seven plus three', output: 10 },
  { input: 'calculate five times six', output: 30 },
  { input: 'find eight divided by four', output: 2 },
  { input: 'what will I get if I multiply 3 with 8', output: 24 },
  { input: 'what is the sum of 12 and 8', output: 20 },
  { input: 'subtract 7 from 15', output: 8 },
  { input: 'what happens when you add 9 to 6', output: 15 },
  { input: 'how much do you get from 4 times 8', output: 32 },
  { input: 'what is the result of 18 minus 9', output: 9 },
  { input: 'tell me 25 divided by 5', output: 5 },
  { input: 'compute 7 plus 8', output: 15 },
  { input: 'work out 6 times 9', output: 54 },

  // Mixed natural language variations
  { input: 'please calculate 3 plus 7', output: 10 },
  { input: 'can you tell me 8 minus 5', output: 3 },
  { input: 'I need to know 4 times 6', output: 24 },
  { input: 'help me find 20 divided by 4', output: 5 },
  { input: 'show me the answer to 5 plus 9', output: 14 },
  { input: 'what would be 7 times 4', output: 28 },
  { input: 'could you solve 16 minus 7', output: 9 },
  { input: 'determine 36 divided by 6', output: 6 },

  // Edge cases and variations (expanded)
  { input: '0+1', output: 1 },
  { input: '0+2', output: 2 },
  { input: '0+5', output: 5 },
  { input: '0+10', output: 10 },
  { input: '1+0', output: 1 },
  { input: '5+0', output: 5 },
  { input: '10-0', output: 10 },
  { input: '15-0', output: 15 },
  { input: '20-0', output: 20 },
  { input: '1*0', output: 0 },
  { input: '0*1', output: 0 },
  { input: '0*5', output: 0 },
  { input: '0*10', output: 0 },
  { input: '1*1', output: 1 },
  { input: '1*5', output: 5 },
  { input: '1*9', output: 9 },
  { input: '5/1', output: 5 },
  { input: '10/1', output: 10 },
  { input: '12/1', output: 12 },
  { input: '15/1', output: 15 },
  { input: '1^1', output: 1 },
  { input: '1^2', output: 1 },
  { input: '1^5', output: 1 },
  { input: '0^1', output: 0 },
  { input: '0^2', output: 0 },
  { input: '0^5', output: 0 },

  // Same operation, different phrasing
  { input: 'what is 2 added to 8', output: 10 },
  { input: 'find 2 increased by 8', output: 10 },
  { input: 'calculate 2 and 8 combined', output: 10 },
  { input: 'what is 12 reduced by 4', output: 8 },
  { input: 'find 12 decreased by 4', output: 8 },
  { input: 'what is 12 less 4', output: 8 },
  { input: 'what is 3 repeated 5 times', output: 15 },
  { input: 'find 3 taken 5 times', output: 15 },
  { input: 'calculate 3 counted 5 times', output: 15 },
];
